# Generated by Django 5.2.2 on 2026-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ameneties_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
